tasks:
  - init: cd client && npm i
  - init: cd functions && npm i
  - init: cd test && npm i
    command: cd test && npm test

vscode:
  extensions:
    - CoenraadS.bracket-pair-colorizer-2@0.1.4:+JUeb/jFYZt2/0MS/gUllA==
    - zhuangtongfa.material-theme@3.8.5:g0hzCQNjVo4tGZHXf+w5Mg==
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - dsznajder.es7-react-js-snippets@2.8.3:MZFzngN6QMMcVWw8QkIFOQ==
    - wmaurer.change-case@1.0.0:EFbL568cjs07Ajw2vuXcpw==
    - maptz.camelcasenavigation@1.1.3:xBNgbjnhbTFpUpCrhaZu/A==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - GitHub.vscode-pull-request-github@0.19.0:7pSNxpy7k9vqog/b6PEJ3w==
    - ExodiusStudios.comment-anchors@1.8.0:kHZMPRTBilSxvpDM8DetyA==
    - vscode.git@1.48.1:a+3btv1sZOaRhNKJx9Qw1g==
